// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Message containing information about the result of an upgrade check
/// operation.
public struct CheckUpgradeResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Url for a docker build log of an upgraded image.
  public var buildLogUri: Swift.String = Swift.String()

  /// Output only. Whether build has succeeded or failed on modules conflicts.
  public var containsPypiModulesConflict: CheckUpgradeResponse.ConflictResult =
    CheckUpgradeResponse.ConflictResult()

  /// Output only. Extract from a docker image build log containing information
  /// about pypi modules conflicts.
  public var pypiConflictBuildLogExtract: Swift.String = Swift.String()

  /// Composer image for which the build was happening.
  public var imageVersion: Swift.String = Swift.String()

  /// Pypi dependencies specified in the environment configuration, at the time
  /// when the build was triggered.
  public var pypiDependencies: [Swift.String: Swift.String] = [:]

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CheckUpgradeResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CheckUpgradeResponse().with { $0.buildLogUri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let buildLogUri = CodingKeys(stringValue: "buildLogUri")
    static let containsPypiModulesConflict = CodingKeys(stringValue: "containsPypiModulesConflict")
    static let pypiConflictBuildLogExtract = CodingKeys(stringValue: "pypiConflictBuildLogExtract")
    static let imageVersion = CodingKeys(stringValue: "imageVersion")
    static let pypiDependencies = CodingKeys(stringValue: "pypiDependencies")

    static let _knownKeys: Set<Swift.String> = [
      "buildLogUri",
      "containsPypiModulesConflict",
      "pypiConflictBuildLogExtract",
      "imageVersion",
      "pypiDependencies",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .buildLogUri) {
      self.buildLogUri = value
    }
    if let value = try container.decodeIfPresent(
      CheckUpgradeResponse.ConflictResult.self, forKey: .containsPypiModulesConflict)
    {
      self.containsPypiModulesConflict = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .pypiConflictBuildLogExtract)
    {
      self.pypiConflictBuildLogExtract = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .imageVersion) {
      self.imageVersion = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .pypiDependencies)
    {
      self.pypiDependencies = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.buildLogUri, forKey: .buildLogUri)
    try container.encode(self.containsPypiModulesConflict, forKey: .containsPypiModulesConflict)
    try container.encode(self.pypiConflictBuildLogExtract, forKey: .pypiConflictBuildLogExtract)
    try container.encode(self.imageVersion, forKey: .imageVersion)
    try container.encode(self.pypiDependencies, forKey: .pypiDependencies)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Whether there were python modules conflict during image build.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum ConflictResult: Codable, Equatable, Hashable, Sendable {
    /// It is unknown whether build had conflicts or not.
    case unspecified
    /// There were python packages conflicts.
    case conflict
    /// There were no python packages conflicts.
    case noConflict
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .conflict: return 1
      case .noConflict: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CONFLICT_RESULT_UNSPECIFIED"
      case .conflict: return "CONFLICT"
      case .noConflict: return "NO_CONFLICT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ConflictResult/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CONFLICT_RESULT_UNSPECIFIED": self = .unspecified
      case "CONFLICT": self = .conflict
      case "NO_CONFLICT": self = .noConflict
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ConflictResult/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .conflict
      case 2: self = .noConflict
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("CONFLICT_RESULT_UNSPECIFIED")
      case .conflict: return try container.encode("CONFLICT")
      case .noConflict: return try container.encode("NO_CONFLICT")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The type URL for `CheckUpgradeResponse`: `"type.googleapis.com/google.cloud.orchestration.airflow.service.v1.CheckUpgradeResponse"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.CheckUpgradeResponse"
  }

  /// Initialize an instance of `CheckUpgradeResponse` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.orchestration.airflow.service.v1.CheckUpgradeResponse"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `CheckUpgradeResponse` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
