// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The configuration setting for Airflow database data retention mechanism.
public struct DataRetentionConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. The retention policy for airflow metadata database.
  public var airflowMetadataRetentionConfig: AirflowMetadataRetentionPolicyConfig? = nil

  /// Optional. The configuration settings for task logs retention
  public var taskLogsRetentionConfig: TaskLogsRetentionConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DataRetentionConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataRetentionConfig().with { $0.airflowMetadataRetentionConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let airflowMetadataRetentionConfig = CodingKeys(
      stringValue: "airflowMetadataRetentionConfig")
    static let taskLogsRetentionConfig = CodingKeys(stringValue: "taskLogsRetentionConfig")

    static let _knownKeys: Set<Swift.String> = [
      "airflowMetadataRetentionConfig",
      "taskLogsRetentionConfig",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.airflowMetadataRetentionConfig = try container.decodeIfPresent(
      AirflowMetadataRetentionPolicyConfig.self, forKey: .airflowMetadataRetentionConfig)
    self.taskLogsRetentionConfig = try container.decodeIfPresent(
      TaskLogsRetentionConfig.self, forKey: .taskLogsRetentionConfig)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(
      self.airflowMetadataRetentionConfig, forKey: .airflowMetadataRetentionConfig)
    try container.encodeIfPresent(self.taskLogsRetentionConfig, forKey: .taskLogsRetentionConfig)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.DataRetentionConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
