// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// Managed Apache Airflow Environments.
///
/// @Snippet(path: "EnvironmentsQuickstart")
public final class EnvironmentsClient: Clients.EnvironmentsProtocol, Sendable {
  let inner: any Clients.EnvironmentsStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.PollingBackoffPolicy

  /// Creates a new `EnvironmentsClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.EnvironmentsStub = try Clients.EnvironmentsTransport(options)
    inner = Clients.EnvironmentsRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.EnvironmentsLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Create a new environment.
  ///
  /// @Snippet(path: "Environments_CreateEnvironment")
  public func createEnvironment(
    request: CreateEnvironmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createEnvironment(request: request, options: options)
  }

  /// Create a new environment.
  ///
  /// @Snippet(path: "Environments_CreateEnvironment")
  public func createEnvironmentPollingUntilDone(
    request: CreateEnvironmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> Environment {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Environment>.State in
      return try op._extractStatus(Environment.self)
    }
    let rawOp = try await self.createEnvironment(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Environment>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Get an existing environment.
  ///
  /// @Snippet(path: "Environments_GetEnvironment")
  public func getEnvironment(
    request: GetEnvironmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.Environment {
    try await self.inner.getEnvironment(request: request, options: options)
  }

  /// List environments.
  ///
  /// @Snippet(path: "Environments_ListEnvironments")
  public func listEnvironments(
    request: ListEnvironmentsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListEnvironmentsResponse {
    try await self.inner.listEnvironments(request: request, options: options)
  }

  /// Update an environment.
  ///
  /// @Snippet(path: "Environments_UpdateEnvironment")
  public func updateEnvironment(
    request: UpdateEnvironmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateEnvironment(request: request, options: options)
  }

  /// Update an environment.
  ///
  /// @Snippet(path: "Environments_UpdateEnvironment")
  public func updateEnvironmentPollingUntilDone(
    request: UpdateEnvironmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> Environment {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Environment>.State in
      return try op._extractStatus(Environment.self)
    }
    let rawOp = try await self.updateEnvironment(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Environment>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Delete an environment.
  ///
  /// @Snippet(path: "Environments_DeleteEnvironment")
  public func deleteEnvironment(
    request: DeleteEnvironmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteEnvironment(request: request, options: options)
  }

  /// Delete an environment.
  ///
  /// @Snippet(path: "Environments_DeleteEnvironment")
  public func deleteEnvironmentPollingUntilDone(
    request: DeleteEnvironmentRequest, options: GoogleGax.RequestOptions
  ) async throws {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteEnvironment(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    try await poller.wait()
  }

  /// Executes Airflow CLI command.
  ///
  /// @Snippet(path: "Environments_ExecuteAirflowCommand")
  public func executeAirflowCommand(
    request: ExecuteAirflowCommandRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ExecuteAirflowCommandResponse {
    try await self.inner.executeAirflowCommand(request: request, options: options)
  }

  /// Stops Airflow CLI command execution.
  ///
  /// @Snippet(path: "Environments_StopAirflowCommand")
  public func stopAirflowCommand(
    request: StopAirflowCommandRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.StopAirflowCommandResponse {
    try await self.inner.stopAirflowCommand(request: request, options: options)
  }

  /// Polls Airflow CLI command execution and fetches logs.
  ///
  /// @Snippet(path: "Environments_PollAirflowCommand")
  public func pollAirflowCommand(
    request: PollAirflowCommandRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.PollAirflowCommandResponse {
    try await self.inner.pollAirflowCommand(request: request, options: options)
  }

  /// Lists workloads in a Cloud Composer environment. Workload is a unit that
  /// runs a single Composer component.
  ///
  /// This method is supported for Cloud Composer environments in versions
  /// composer-2.*.*-airflow-*.*.* and newer.
  ///
  /// @Snippet(path: "Environments_ListWorkloads")
  public func listWorkloads(
    request: ListWorkloadsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListWorkloadsResponse {
    try await self.inner.listWorkloads(request: request, options: options)
  }

  /// Check if an upgrade operation on the environment will succeed.
  ///
  /// In case of problems detailed info can be found in the returned Operation.
  ///
  /// @Snippet(path: "Environments_CheckUpgrade")
  public func checkUpgrade(
    request: CheckUpgradeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.checkUpgrade(request: request, options: options)
  }

  /// Check if an upgrade operation on the environment will succeed.
  ///
  /// In case of problems detailed info can be found in the returned Operation.
  ///
  /// @Snippet(path: "Environments_CheckUpgrade")
  public func checkUpgradePollingUntilDone(
    request: CheckUpgradeRequest, options: GoogleGax.RequestOptions
  ) async throws -> CheckUpgradeResponse {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<CheckUpgradeResponse>.State in
      return try op._extractStatus(CheckUpgradeResponse.self)
    }
    let rawOp = try await self.checkUpgrade(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<CheckUpgradeResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Creates a user workloads Secret.
  ///
  /// This method is supported for Cloud Composer environments in versions
  /// composer-3-airflow-*.*.*-build.* and newer.
  ///
  /// @Snippet(path: "Environments_CreateUserWorkloadsSecret")
  public func createUserWorkloadsSecret(
    request: CreateUserWorkloadsSecretRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret {
    try await self.inner.createUserWorkloadsSecret(request: request, options: options)
  }

  /// Gets an existing user workloads Secret.
  /// Values of the "data" field in the response are cleared.
  ///
  /// This method is supported for Cloud Composer environments in versions
  /// composer-3-airflow-*.*.*-build.* and newer.
  ///
  /// @Snippet(path: "Environments_GetUserWorkloadsSecret")
  public func getUserWorkloadsSecret(
    request: GetUserWorkloadsSecretRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret {
    try await self.inner.getUserWorkloadsSecret(request: request, options: options)
  }

  /// Lists user workloads Secrets.
  ///
  /// This method is supported for Cloud Composer environments in versions
  /// composer-3-airflow-*.*.*-build.* and newer.
  ///
  /// @Snippet(path: "Environments_ListUserWorkloadsSecrets")
  public func listUserWorkloadsSecrets(
    request: ListUserWorkloadsSecretsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListUserWorkloadsSecretsResponse {
    try await self.inner.listUserWorkloadsSecrets(request: request, options: options)
  }

  /// Updates a user workloads Secret.
  ///
  /// This method is supported for Cloud Composer environments in versions
  /// composer-3-airflow-*.*.*-build.* and newer.
  ///
  /// @Snippet(path: "Environments_UpdateUserWorkloadsSecret")
  public func updateUserWorkloadsSecret(
    request: UpdateUserWorkloadsSecretRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret {
    try await self.inner.updateUserWorkloadsSecret(request: request, options: options)
  }

  /// Deletes a user workloads Secret.
  ///
  /// This method is supported for Cloud Composer environments in versions
  /// composer-3-airflow-*.*.*-build.* and newer.
  ///
  /// @Snippet(path: "Environments_DeleteUserWorkloadsSecret")
  public func deleteUserWorkloadsSecret(
    request: DeleteUserWorkloadsSecretRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteUserWorkloadsSecret(request: request, options: options)
  }

  /// Creates a user workloads ConfigMap.
  ///
  /// This method is supported for Cloud Composer environments in versions
  /// composer-3-airflow-*.*.*-build.* and newer.
  ///
  /// @Snippet(path: "Environments_CreateUserWorkloadsConfigMap")
  public func createUserWorkloadsConfigMap(
    request: CreateUserWorkloadsConfigMapRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap {
    try await self.inner.createUserWorkloadsConfigMap(request: request, options: options)
  }

  /// Gets an existing user workloads ConfigMap.
  ///
  /// This method is supported for Cloud Composer environments in versions
  /// composer-3-airflow-*.*.*-build.* and newer.
  ///
  /// @Snippet(path: "Environments_GetUserWorkloadsConfigMap")
  public func getUserWorkloadsConfigMap(
    request: GetUserWorkloadsConfigMapRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap {
    try await self.inner.getUserWorkloadsConfigMap(request: request, options: options)
  }

  /// Lists user workloads ConfigMaps.
  ///
  /// This method is supported for Cloud Composer environments in versions
  /// composer-3-airflow-*.*.*-build.* and newer.
  ///
  /// @Snippet(path: "Environments_ListUserWorkloadsConfigMaps")
  public func listUserWorkloadsConfigMaps(
    request: ListUserWorkloadsConfigMapsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListUserWorkloadsConfigMapsResponse {
    try await self.inner.listUserWorkloadsConfigMaps(request: request, options: options)
  }

  /// Updates a user workloads ConfigMap.
  ///
  /// This method is supported for Cloud Composer environments in versions
  /// composer-3-airflow-*.*.*-build.* and newer.
  ///
  /// @Snippet(path: "Environments_UpdateUserWorkloadsConfigMap")
  public func updateUserWorkloadsConfigMap(
    request: UpdateUserWorkloadsConfigMapRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap {
    try await self.inner.updateUserWorkloadsConfigMap(request: request, options: options)
  }

  /// Deletes a user workloads ConfigMap.
  ///
  /// This method is supported for Cloud Composer environments in versions
  /// composer-3-airflow-*.*.*-build.* and newer.
  ///
  /// @Snippet(path: "Environments_DeleteUserWorkloadsConfigMap")
  public func deleteUserWorkloadsConfigMap(
    request: DeleteUserWorkloadsConfigMapRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteUserWorkloadsConfigMap(request: request, options: options)
  }

  /// Creates a snapshots of a Cloud Composer environment.
  ///
  /// As a result of this operation, snapshot of environment's state is stored
  /// in a location specified in the SaveSnapshotRequest.
  ///
  /// @Snippet(path: "Environments_SaveSnapshot")
  public func saveSnapshot(
    request: SaveSnapshotRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.saveSnapshot(request: request, options: options)
  }

  /// Creates a snapshots of a Cloud Composer environment.
  ///
  /// As a result of this operation, snapshot of environment's state is stored
  /// in a location specified in the SaveSnapshotRequest.
  ///
  /// @Snippet(path: "Environments_SaveSnapshot")
  public func saveSnapshotPollingUntilDone(
    request: SaveSnapshotRequest, options: GoogleGax.RequestOptions
  ) async throws -> SaveSnapshotResponse {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<SaveSnapshotResponse>.State in
      return try op._extractStatus(SaveSnapshotResponse.self)
    }
    let rawOp = try await self.saveSnapshot(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<SaveSnapshotResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Loads a snapshot of a Cloud Composer environment.
  ///
  /// As a result of this operation, a snapshot of environment's specified in
  /// LoadSnapshotRequest is loaded into the environment.
  ///
  /// @Snippet(path: "Environments_LoadSnapshot")
  public func loadSnapshot(
    request: LoadSnapshotRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.loadSnapshot(request: request, options: options)
  }

  /// Loads a snapshot of a Cloud Composer environment.
  ///
  /// As a result of this operation, a snapshot of environment's specified in
  /// LoadSnapshotRequest is loaded into the environment.
  ///
  /// @Snippet(path: "Environments_LoadSnapshot")
  public func loadSnapshotPollingUntilDone(
    request: LoadSnapshotRequest, options: GoogleGax.RequestOptions
  ) async throws -> LoadSnapshotResponse {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<LoadSnapshotResponse>.State in
      return try op._extractStatus(LoadSnapshotResponse.self)
    }
    let rawOp = try await self.loadSnapshot(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<LoadSnapshotResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Triggers database failover (only for highly resilient environments).
  ///
  /// @Snippet(path: "Environments_DatabaseFailover")
  public func databaseFailover(
    request: DatabaseFailoverRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.databaseFailover(request: request, options: options)
  }

  /// Triggers database failover (only for highly resilient environments).
  ///
  /// @Snippet(path: "Environments_DatabaseFailover")
  public func databaseFailoverPollingUntilDone(
    request: DatabaseFailoverRequest, options: GoogleGax.RequestOptions
  ) async throws -> DatabaseFailoverResponse {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<DatabaseFailoverResponse>.State in
      return try op._extractStatus(DatabaseFailoverResponse.self)
    }
    let rawOp = try await self.databaseFailover(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<DatabaseFailoverResponse>.State
      in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Fetches database properties.
  ///
  /// @Snippet(path: "Environments_FetchDatabaseProperties")
  public func fetchDatabaseProperties(
    request: FetchDatabasePropertiesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.FetchDatabasePropertiesResponse {
    try await self.inner.fetchDatabaseProperties(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Environments_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Environments_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Environments_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `EnvironmentsClient`.
  ///
  /// To mock `EnvironmentsClient` change your functions to receive
  /// `some EnvironmentsProtocol` or `any EnvironmentsProtocol`
  /// and pass a mock implementation in your tests.
  public protocol EnvironmentsProtocol: Sendable {
    /// See `EnvironmentsClient.createEnvironment`.
    func createEnvironment(
      request: CreateEnvironmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `EnvironmentsClient.createEnvironment`.
    func createEnvironmentPollingUntilDone(
      request: CreateEnvironmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> Environment

    /// See `EnvironmentsClient.getEnvironment`.
    func getEnvironment(
      request: GetEnvironmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.Environment

    /// See `EnvironmentsClient.listEnvironments`.
    func listEnvironments(
      request: ListEnvironmentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListEnvironmentsResponse

    /// See `EnvironmentsClient.updateEnvironment`.
    func updateEnvironment(
      request: UpdateEnvironmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `EnvironmentsClient.updateEnvironment`.
    func updateEnvironmentPollingUntilDone(
      request: UpdateEnvironmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> Environment

    /// See `EnvironmentsClient.deleteEnvironment`.
    func deleteEnvironment(
      request: DeleteEnvironmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `EnvironmentsClient.deleteEnvironment`.
    func deleteEnvironmentPollingUntilDone(
      request: DeleteEnvironmentRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `EnvironmentsClient.executeAirflowCommand`.
    func executeAirflowCommand(
      request: ExecuteAirflowCommandRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ExecuteAirflowCommandResponse

    /// See `EnvironmentsClient.stopAirflowCommand`.
    func stopAirflowCommand(
      request: StopAirflowCommandRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.StopAirflowCommandResponse

    /// See `EnvironmentsClient.pollAirflowCommand`.
    func pollAirflowCommand(
      request: PollAirflowCommandRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.PollAirflowCommandResponse

    /// See `EnvironmentsClient.listWorkloads`.
    func listWorkloads(
      request: ListWorkloadsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListWorkloadsResponse

    /// See `EnvironmentsClient.checkUpgrade`.
    func checkUpgrade(
      request: CheckUpgradeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `EnvironmentsClient.checkUpgrade`.
    func checkUpgradePollingUntilDone(
      request: CheckUpgradeRequest, options: GoogleGax.RequestOptions
    ) async throws -> CheckUpgradeResponse

    /// See `EnvironmentsClient.createUserWorkloadsSecret`.
    func createUserWorkloadsSecret(
      request: CreateUserWorkloadsSecretRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret

    /// See `EnvironmentsClient.getUserWorkloadsSecret`.
    func getUserWorkloadsSecret(
      request: GetUserWorkloadsSecretRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret

    /// See `EnvironmentsClient.listUserWorkloadsSecrets`.
    func listUserWorkloadsSecrets(
      request: ListUserWorkloadsSecretsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListUserWorkloadsSecretsResponse

    /// See `EnvironmentsClient.updateUserWorkloadsSecret`.
    func updateUserWorkloadsSecret(
      request: UpdateUserWorkloadsSecretRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret

    /// See `EnvironmentsClient.deleteUserWorkloadsSecret`.
    func deleteUserWorkloadsSecret(
      request: DeleteUserWorkloadsSecretRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `EnvironmentsClient.createUserWorkloadsConfigMap`.
    func createUserWorkloadsConfigMap(
      request: CreateUserWorkloadsConfigMapRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap

    /// See `EnvironmentsClient.getUserWorkloadsConfigMap`.
    func getUserWorkloadsConfigMap(
      request: GetUserWorkloadsConfigMapRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap

    /// See `EnvironmentsClient.listUserWorkloadsConfigMaps`.
    func listUserWorkloadsConfigMaps(
      request: ListUserWorkloadsConfigMapsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListUserWorkloadsConfigMapsResponse

    /// See `EnvironmentsClient.updateUserWorkloadsConfigMap`.
    func updateUserWorkloadsConfigMap(
      request: UpdateUserWorkloadsConfigMapRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap

    /// See `EnvironmentsClient.deleteUserWorkloadsConfigMap`.
    func deleteUserWorkloadsConfigMap(
      request: DeleteUserWorkloadsConfigMapRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `EnvironmentsClient.saveSnapshot`.
    func saveSnapshot(
      request: SaveSnapshotRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `EnvironmentsClient.saveSnapshot`.
    func saveSnapshotPollingUntilDone(
      request: SaveSnapshotRequest, options: GoogleGax.RequestOptions
    ) async throws -> SaveSnapshotResponse

    /// See `EnvironmentsClient.loadSnapshot`.
    func loadSnapshot(
      request: LoadSnapshotRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `EnvironmentsClient.loadSnapshot`.
    func loadSnapshotPollingUntilDone(
      request: LoadSnapshotRequest, options: GoogleGax.RequestOptions
    ) async throws -> LoadSnapshotResponse

    /// See `EnvironmentsClient.databaseFailover`.
    func databaseFailover(
      request: DatabaseFailoverRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `EnvironmentsClient.databaseFailover`.
    func databaseFailoverPollingUntilDone(
      request: DatabaseFailoverRequest, options: GoogleGax.RequestOptions
    ) async throws -> DatabaseFailoverResponse

    /// See `EnvironmentsClient.fetchDatabaseProperties`.
    func fetchDatabaseProperties(
      request: FetchDatabasePropertiesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.FetchDatabasePropertiesResponse

    /// See `EnvironmentsClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `EnvironmentsClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.EnvironmentsProtocol {
  public func createEnvironment(request: CreateEnvironmentRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createEnvironment(request: request, options: .init())
  }

  public func createEnvironment(
    request: CreateEnvironmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createEnvironmentPollingUntilDone(request: CreateEnvironmentRequest) async throws
    -> Environment
  {
    return try await self.createEnvironmentPollingUntilDone(request: request, options: .init())
  }

  public func createEnvironmentPollingUntilDone(
    request: CreateEnvironmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> Environment {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createEnvironmentPollingUntilDone(
    parent: Swift.String,
    environment: Environment?,
  ) async throws -> Environment {
    let request = CreateEnvironmentRequest().with {
      $0.parent = parent
      $0.environment = environment
    }
    return try await self.createEnvironmentPollingUntilDone(request: request)
  }

  public func getEnvironment(request: GetEnvironmentRequest) async throws
    -> GoogleCloudOrchestrationAirflowServiceV1.Environment
  {
    try await self.getEnvironment(request: request, options: .init())
  }

  public func getEnvironment(
    request: GetEnvironmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.Environment {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getEnvironment(
    name: Swift.String,
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.Environment {
    let request = GetEnvironmentRequest().with {
      $0.name = name
    }
    return try await self.getEnvironment(request: request)
  }

  public func listEnvironments(request: ListEnvironmentsRequest) async throws
    -> GoogleCloudOrchestrationAirflowServiceV1.ListEnvironmentsResponse
  {
    try await self.listEnvironments(request: request, options: .init())
  }

  public func listEnvironments(
    request: ListEnvironmentsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListEnvironmentsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listEnvironmentsByItems(
    request: ListEnvironmentsRequest
  ) -> some AsyncSequence<Environment, Swift.Error> & Sendable {
    self.listEnvironmentsByItems(request: request, options: .init())
  }

  /// List environments.
  ///
  /// @Snippet(path: "Environments_ListEnvironments")
  public func listEnvironmentsByItems(
    request: ListEnvironmentsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<Environment, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudOrchestrationAirflowServiceV1.ListEnvironmentsResponse in
      var request = request
      request.pageToken = token
      return try await self.listEnvironments(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listEnvironmentsByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<Environment, Swift.Error> & Sendable {
    let request = ListEnvironmentsRequest().with {
      $0.parent = parent
    }
    return self.listEnvironmentsByItems(request: request)
  }

  public func updateEnvironment(request: UpdateEnvironmentRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateEnvironment(request: request, options: .init())
  }

  public func updateEnvironment(
    request: UpdateEnvironmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateEnvironmentPollingUntilDone(request: UpdateEnvironmentRequest) async throws
    -> Environment
  {
    return try await self.updateEnvironmentPollingUntilDone(request: request, options: .init())
  }

  public func updateEnvironmentPollingUntilDone(
    request: UpdateEnvironmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> Environment {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateEnvironmentPollingUntilDone(
    name: Swift.String,
    environment: Environment?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> Environment {
    let request = UpdateEnvironmentRequest().with {
      $0.name = name
      $0.environment = environment
      $0.updateMask = updateMask
    }
    return try await self.updateEnvironmentPollingUntilDone(request: request)
  }

  public func deleteEnvironment(request: DeleteEnvironmentRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteEnvironment(request: request, options: .init())
  }

  public func deleteEnvironment(
    request: DeleteEnvironmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteEnvironmentPollingUntilDone(request: DeleteEnvironmentRequest) async throws {
    try await self.deleteEnvironmentPollingUntilDone(request: request, options: .init())
  }

  public func deleteEnvironmentPollingUntilDone(
    request: DeleteEnvironmentRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteEnvironmentPollingUntilDone(
    name: Swift.String,
  ) async throws {
    let request = DeleteEnvironmentRequest().with {
      $0.name = name
    }
    try await self.deleteEnvironmentPollingUntilDone(request: request)
  }

  public func executeAirflowCommand(request: ExecuteAirflowCommandRequest) async throws
    -> GoogleCloudOrchestrationAirflowServiceV1.ExecuteAirflowCommandResponse
  {
    try await self.executeAirflowCommand(request: request, options: .init())
  }

  public func executeAirflowCommand(
    request: ExecuteAirflowCommandRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ExecuteAirflowCommandResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func stopAirflowCommand(request: StopAirflowCommandRequest) async throws
    -> GoogleCloudOrchestrationAirflowServiceV1.StopAirflowCommandResponse
  {
    try await self.stopAirflowCommand(request: request, options: .init())
  }

  public func stopAirflowCommand(
    request: StopAirflowCommandRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.StopAirflowCommandResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func pollAirflowCommand(request: PollAirflowCommandRequest) async throws
    -> GoogleCloudOrchestrationAirflowServiceV1.PollAirflowCommandResponse
  {
    try await self.pollAirflowCommand(request: request, options: .init())
  }

  public func pollAirflowCommand(
    request: PollAirflowCommandRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.PollAirflowCommandResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listWorkloads(request: ListWorkloadsRequest) async throws
    -> GoogleCloudOrchestrationAirflowServiceV1.ListWorkloadsResponse
  {
    try await self.listWorkloads(request: request, options: .init())
  }

  public func listWorkloads(
    request: ListWorkloadsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListWorkloadsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listWorkloadsByItems(
    request: ListWorkloadsRequest
  ) -> some AsyncSequence<ListWorkloadsResponse.ComposerWorkload, Swift.Error> & Sendable {
    self.listWorkloadsByItems(request: request, options: .init())
  }

  /// Lists workloads in a Cloud Composer environment. Workload is a unit that
  /// runs a single Composer component.
  ///
  /// This method is supported for Cloud Composer environments in versions
  /// composer-2.*.*-airflow-*.*.* and newer.
  ///
  /// @Snippet(path: "Environments_ListWorkloads")
  public func listWorkloadsByItems(
    request: ListWorkloadsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<ListWorkloadsResponse.ComposerWorkload, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudOrchestrationAirflowServiceV1.ListWorkloadsResponse in
      var request = request
      request.pageToken = token
      return try await self.listWorkloads(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listWorkloadsByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<ListWorkloadsResponse.ComposerWorkload, Swift.Error> & Sendable {
    let request = ListWorkloadsRequest().with {
      $0.parent = parent
    }
    return self.listWorkloadsByItems(request: request)
  }

  public func checkUpgrade(request: CheckUpgradeRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.checkUpgrade(request: request, options: .init())
  }

  public func checkUpgrade(
    request: CheckUpgradeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func checkUpgradePollingUntilDone(request: CheckUpgradeRequest) async throws
    -> CheckUpgradeResponse
  {
    return try await self.checkUpgradePollingUntilDone(request: request, options: .init())
  }

  public func checkUpgradePollingUntilDone(
    request: CheckUpgradeRequest, options: GoogleGax.RequestOptions
  ) async throws -> CheckUpgradeResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createUserWorkloadsSecret(request: CreateUserWorkloadsSecretRequest) async throws
    -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret
  {
    try await self.createUserWorkloadsSecret(request: request, options: .init())
  }

  public func createUserWorkloadsSecret(
    request: CreateUserWorkloadsSecretRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createUserWorkloadsSecret(
    parent: Swift.String,
    userWorkloadsSecret: UserWorkloadsSecret?,
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret {
    let request = CreateUserWorkloadsSecretRequest().with {
      $0.parent = parent
      $0.userWorkloadsSecret = userWorkloadsSecret
    }
    return try await self.createUserWorkloadsSecret(request: request)
  }

  public func getUserWorkloadsSecret(request: GetUserWorkloadsSecretRequest) async throws
    -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret
  {
    try await self.getUserWorkloadsSecret(request: request, options: .init())
  }

  public func getUserWorkloadsSecret(
    request: GetUserWorkloadsSecretRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getUserWorkloadsSecret(
    name: Swift.String,
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret {
    let request = GetUserWorkloadsSecretRequest().with {
      $0.name = name
    }
    return try await self.getUserWorkloadsSecret(request: request)
  }

  public func listUserWorkloadsSecrets(request: ListUserWorkloadsSecretsRequest) async throws
    -> GoogleCloudOrchestrationAirflowServiceV1.ListUserWorkloadsSecretsResponse
  {
    try await self.listUserWorkloadsSecrets(request: request, options: .init())
  }

  public func listUserWorkloadsSecrets(
    request: ListUserWorkloadsSecretsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListUserWorkloadsSecretsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listUserWorkloadsSecretsByItems(
    request: ListUserWorkloadsSecretsRequest
  ) -> some AsyncSequence<UserWorkloadsSecret, Swift.Error> & Sendable {
    self.listUserWorkloadsSecretsByItems(request: request, options: .init())
  }

  /// Lists user workloads Secrets.
  ///
  /// This method is supported for Cloud Composer environments in versions
  /// composer-3-airflow-*.*.*-build.* and newer.
  ///
  /// @Snippet(path: "Environments_ListUserWorkloadsSecrets")
  public func listUserWorkloadsSecretsByItems(
    request: ListUserWorkloadsSecretsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<UserWorkloadsSecret, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudOrchestrationAirflowServiceV1.ListUserWorkloadsSecretsResponse in
      var request = request
      request.pageToken = token
      return try await self.listUserWorkloadsSecrets(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listUserWorkloadsSecretsByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<UserWorkloadsSecret, Swift.Error> & Sendable {
    let request = ListUserWorkloadsSecretsRequest().with {
      $0.parent = parent
    }
    return self.listUserWorkloadsSecretsByItems(request: request)
  }

  public func updateUserWorkloadsSecret(request: UpdateUserWorkloadsSecretRequest) async throws
    -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret
  {
    try await self.updateUserWorkloadsSecret(request: request, options: .init())
  }

  public func updateUserWorkloadsSecret(
    request: UpdateUserWorkloadsSecretRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateUserWorkloadsSecret(
    userWorkloadsSecret: UserWorkloadsSecret?,
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsSecret {
    let request = UpdateUserWorkloadsSecretRequest().with {
      $0.userWorkloadsSecret = userWorkloadsSecret
    }
    return try await self.updateUserWorkloadsSecret(request: request)
  }

  public func deleteUserWorkloadsSecret(request: DeleteUserWorkloadsSecretRequest) async throws {
    try await self.deleteUserWorkloadsSecret(request: request, options: .init())
  }

  public func deleteUserWorkloadsSecret(
    request: DeleteUserWorkloadsSecretRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteUserWorkloadsSecret(
    name: Swift.String,
  ) async throws {
    let request = DeleteUserWorkloadsSecretRequest().with {
      $0.name = name
    }
    try await self.deleteUserWorkloadsSecret(request: request)
  }

  public func createUserWorkloadsConfigMap(request: CreateUserWorkloadsConfigMapRequest)
    async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap
  {
    try await self.createUserWorkloadsConfigMap(request: request, options: .init())
  }

  public func createUserWorkloadsConfigMap(
    request: CreateUserWorkloadsConfigMapRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createUserWorkloadsConfigMap(
    parent: Swift.String,
    userWorkloadsConfigMap: UserWorkloadsConfigMap?,
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap {
    let request = CreateUserWorkloadsConfigMapRequest().with {
      $0.parent = parent
      $0.userWorkloadsConfigMap = userWorkloadsConfigMap
    }
    return try await self.createUserWorkloadsConfigMap(request: request)
  }

  public func getUserWorkloadsConfigMap(request: GetUserWorkloadsConfigMapRequest) async throws
    -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap
  {
    try await self.getUserWorkloadsConfigMap(request: request, options: .init())
  }

  public func getUserWorkloadsConfigMap(
    request: GetUserWorkloadsConfigMapRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getUserWorkloadsConfigMap(
    name: Swift.String,
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap {
    let request = GetUserWorkloadsConfigMapRequest().with {
      $0.name = name
    }
    return try await self.getUserWorkloadsConfigMap(request: request)
  }

  public func listUserWorkloadsConfigMaps(request: ListUserWorkloadsConfigMapsRequest) async throws
    -> GoogleCloudOrchestrationAirflowServiceV1.ListUserWorkloadsConfigMapsResponse
  {
    try await self.listUserWorkloadsConfigMaps(request: request, options: .init())
  }

  public func listUserWorkloadsConfigMaps(
    request: ListUserWorkloadsConfigMapsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListUserWorkloadsConfigMapsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listUserWorkloadsConfigMapsByItems(
    request: ListUserWorkloadsConfigMapsRequest
  ) -> some AsyncSequence<UserWorkloadsConfigMap, Swift.Error> & Sendable {
    self.listUserWorkloadsConfigMapsByItems(request: request, options: .init())
  }

  /// Lists user workloads ConfigMaps.
  ///
  /// This method is supported for Cloud Composer environments in versions
  /// composer-3-airflow-*.*.*-build.* and newer.
  ///
  /// @Snippet(path: "Environments_ListUserWorkloadsConfigMaps")
  public func listUserWorkloadsConfigMapsByItems(
    request: ListUserWorkloadsConfigMapsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<UserWorkloadsConfigMap, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudOrchestrationAirflowServiceV1.ListUserWorkloadsConfigMapsResponse in
      var request = request
      request.pageToken = token
      return try await self.listUserWorkloadsConfigMaps(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listUserWorkloadsConfigMapsByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<UserWorkloadsConfigMap, Swift.Error> & Sendable {
    let request = ListUserWorkloadsConfigMapsRequest().with {
      $0.parent = parent
    }
    return self.listUserWorkloadsConfigMapsByItems(request: request)
  }

  public func updateUserWorkloadsConfigMap(request: UpdateUserWorkloadsConfigMapRequest)
    async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap
  {
    try await self.updateUserWorkloadsConfigMap(request: request, options: .init())
  }

  public func updateUserWorkloadsConfigMap(
    request: UpdateUserWorkloadsConfigMapRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateUserWorkloadsConfigMap(
    userWorkloadsConfigMap: UserWorkloadsConfigMap?,
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.UserWorkloadsConfigMap {
    let request = UpdateUserWorkloadsConfigMapRequest().with {
      $0.userWorkloadsConfigMap = userWorkloadsConfigMap
    }
    return try await self.updateUserWorkloadsConfigMap(request: request)
  }

  public func deleteUserWorkloadsConfigMap(request: DeleteUserWorkloadsConfigMapRequest)
    async throws
  {
    try await self.deleteUserWorkloadsConfigMap(request: request, options: .init())
  }

  public func deleteUserWorkloadsConfigMap(
    request: DeleteUserWorkloadsConfigMapRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteUserWorkloadsConfigMap(
    name: Swift.String,
  ) async throws {
    let request = DeleteUserWorkloadsConfigMapRequest().with {
      $0.name = name
    }
    try await self.deleteUserWorkloadsConfigMap(request: request)
  }

  public func saveSnapshot(request: SaveSnapshotRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.saveSnapshot(request: request, options: .init())
  }

  public func saveSnapshot(
    request: SaveSnapshotRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func saveSnapshotPollingUntilDone(request: SaveSnapshotRequest) async throws
    -> SaveSnapshotResponse
  {
    return try await self.saveSnapshotPollingUntilDone(request: request, options: .init())
  }

  public func saveSnapshotPollingUntilDone(
    request: SaveSnapshotRequest, options: GoogleGax.RequestOptions
  ) async throws -> SaveSnapshotResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func loadSnapshot(request: LoadSnapshotRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.loadSnapshot(request: request, options: .init())
  }

  public func loadSnapshot(
    request: LoadSnapshotRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func loadSnapshotPollingUntilDone(request: LoadSnapshotRequest) async throws
    -> LoadSnapshotResponse
  {
    return try await self.loadSnapshotPollingUntilDone(request: request, options: .init())
  }

  public func loadSnapshotPollingUntilDone(
    request: LoadSnapshotRequest, options: GoogleGax.RequestOptions
  ) async throws -> LoadSnapshotResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func databaseFailover(request: DatabaseFailoverRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.databaseFailover(request: request, options: .init())
  }

  public func databaseFailover(
    request: DatabaseFailoverRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func databaseFailoverPollingUntilDone(request: DatabaseFailoverRequest) async throws
    -> DatabaseFailoverResponse
  {
    return try await self.databaseFailoverPollingUntilDone(request: request, options: .init())
  }

  public func databaseFailoverPollingUntilDone(
    request: DatabaseFailoverRequest, options: GoogleGax.RequestOptions
  ) async throws -> DatabaseFailoverResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func fetchDatabaseProperties(request: FetchDatabasePropertiesRequest) async throws
    -> GoogleCloudOrchestrationAirflowServiceV1.FetchDatabasePropertiesResponse
  {
    try await self.fetchDatabaseProperties(request: request, options: .init())
  }

  public func fetchDatabaseProperties(
    request: FetchDatabasePropertiesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.FetchDatabasePropertiesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Environments_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }
}
