// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Execute Airflow Command request.
public struct ExecuteAirflowCommandRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The resource name of the environment in the form:
  /// "projects/{projectId}/locations/{locationId}/environments/{environmentId}".
  public var environment: Swift.String = Swift.String()

  /// Airflow command.
  public var command: Swift.String = Swift.String()

  /// Airflow subcommand.
  public var subcommand: Swift.String = Swift.String()

  /// Parameters for the Airflow command/subcommand as an array of arguments.
  /// It may contain positional arguments like `["my-dag-id"]`, key-value
  /// parameters like `["--foo=bar"]` or `["--foo","bar"]`,
  /// or other flags like `["-f"]`.
  public var parameters: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ExecuteAirflowCommandRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ExecuteAirflowCommandRequest().with { $0.environment = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let environment = CodingKeys(stringValue: "environment")
    static let command = CodingKeys(stringValue: "command")
    static let subcommand = CodingKeys(stringValue: "subcommand")
    static let parameters = CodingKeys(stringValue: "parameters")

    static let _knownKeys: Set<Swift.String> = [
      "environment",
      "command",
      "subcommand",
      "parameters",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .environment) {
      self.environment = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .command) {
      self.command = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .subcommand) {
      self.subcommand = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .parameters) {
      self.parameters = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.environment, forKey: .environment)
    try container.encode(self.command, forKey: .command)
    try container.encode(self.subcommand, forKey: .subcommand)
    try container.encode(self.parameters, forKey: .parameters)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.ExecuteAirflowCommandRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
