// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Response for FetchDatabasePropertiesRequest.
public struct FetchDatabasePropertiesResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The Compute Engine zone that the instance is currently serving from.
  public var primaryGceZone: Swift.String = Swift.String()

  /// The Compute Engine zone that the failover instance is currently serving
  /// from for a regional Cloud SQL instance.
  public var secondaryGceZone: Swift.String = Swift.String()

  /// The availability status of the failover replica. A false status indicates
  /// that the failover replica is out of sync. The primary instance can only
  /// fail over to the failover replica when the status is true.
  public var isFailoverReplicaAvailable: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `FetchDatabasePropertiesResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FetchDatabasePropertiesResponse().with { $0.primaryGceZone = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let primaryGceZone = CodingKeys(stringValue: "primaryGceZone")
    static let secondaryGceZone = CodingKeys(stringValue: "secondaryGceZone")
    static let isFailoverReplicaAvailable = CodingKeys(stringValue: "isFailoverReplicaAvailable")

    static let _knownKeys: Set<Swift.String> = [
      "primaryGceZone",
      "secondaryGceZone",
      "isFailoverReplicaAvailable",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .primaryGceZone) {
      self.primaryGceZone = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .secondaryGceZone) {
      self.secondaryGceZone = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .isFailoverReplicaAvailable)
    {
      self.isFailoverReplicaAvailable = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.primaryGceZone, forKey: .primaryGceZone)
    try container.encode(self.secondaryGceZone, forKey: .secondaryGceZone)
    try container.encode(self.isFailoverReplicaAvailable, forKey: .isFailoverReplicaAvailable)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.FetchDatabasePropertiesResponse"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
