// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleType
@_spi(GoogleCloudInternal) public import GoogleWKT

/// ImageVersion information
public struct ImageVersion: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The string identifier of the ImageVersion, in the form:
  /// "composer-x.y.z-airflow-a.b.c"
  public var imageVersionId: Swift.String = Swift.String()

  /// Whether this is the default ImageVersion used by Composer during
  /// environment creation if no input ImageVersion is specified.
  public var isDefault: Swift.Bool = Swift.Bool()

  /// supported python versions
  public var supportedPythonVersions: [Swift.String] = []

  /// The date of the version release.
  public var releaseDate: GoogleType.Date? = nil

  /// Whether it is impossible to create an environment with the image version.
  public var creationDisabled: Swift.Bool = Swift.Bool()

  /// Whether it is impossible to upgrade an environment running with the image
  /// version.
  public var upgradeDisabled: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ImageVersion`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ImageVersion().with { $0.imageVersionId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let imageVersionId = CodingKeys(stringValue: "imageVersionId")
    static let isDefault = CodingKeys(stringValue: "isDefault")
    static let supportedPythonVersions = CodingKeys(stringValue: "supportedPythonVersions")
    static let releaseDate = CodingKeys(stringValue: "releaseDate")
    static let creationDisabled = CodingKeys(stringValue: "creationDisabled")
    static let upgradeDisabled = CodingKeys(stringValue: "upgradeDisabled")

    static let _knownKeys: Set<Swift.String> = [
      "imageVersionId",
      "isDefault",
      "supportedPythonVersions",
      "releaseDate",
      "creationDisabled",
      "upgradeDisabled",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .imageVersionId) {
      self.imageVersionId = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .isDefault) {
      self.isDefault = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String].self, forKey: .supportedPythonVersions)
    {
      self.supportedPythonVersions = value
    }
    self.releaseDate = try container.decodeIfPresent(GoogleType.Date.self, forKey: .releaseDate)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .creationDisabled) {
      self.creationDisabled = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .upgradeDisabled) {
      self.upgradeDisabled = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.imageVersionId, forKey: .imageVersionId)
    try container.encode(self.isDefault, forKey: .isDefault)
    try container.encode(self.supportedPythonVersions, forKey: .supportedPythonVersions)
    try container.encodeIfPresent(self.releaseDate, forKey: .releaseDate)
    try container.encode(self.creationDisabled, forKey: .creationDisabled)
    try container.encode(self.upgradeDisabled, forKey: .upgradeDisabled)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `ImageVersion`: `"type.googleapis.com/google.cloud.orchestration.airflow.service.v1.ImageVersion"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.ImageVersion"
  }

  /// Initialize an instance of `ImageVersion` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.orchestration.airflow.service.v1.ImageVersion"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `ImageVersion` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
