// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleGax

/// Readonly service to query available ImageVersions.
///
/// @Snippet(path: "ImageVersionsQuickstart")
public final class ImageVersionsClient: Clients.ImageVersionsProtocol, Sendable {
  let inner: any Clients.ImageVersionsStub

  /// Creates a new `ImageVersionsClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.ImageVersionsStub = try Clients.ImageVersionsTransport(options)
    inner = Clients.ImageVersionsRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ImageVersionsLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// List ImageVersions for provided location.
  ///
  /// @Snippet(path: "ImageVersions_ListImageVersions")
  public func listImageVersions(
    request: ListImageVersionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListImageVersionsResponse {
    try await self.inner.listImageVersions(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ImageVersions_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ImageVersions_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ImageVersions_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ImageVersionsClient`.
  ///
  /// To mock `ImageVersionsClient` change your functions to receive
  /// `some ImageVersionsProtocol` or `any ImageVersionsProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ImageVersionsProtocol: Sendable {
    /// See `ImageVersionsClient.listImageVersions`.
    func listImageVersions(
      request: ListImageVersionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListImageVersionsResponse

    /// See `ImageVersionsClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `ImageVersionsClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.ImageVersionsProtocol {
  public func listImageVersions(request: ListImageVersionsRequest) async throws
    -> GoogleCloudOrchestrationAirflowServiceV1.ListImageVersionsResponse
  {
    try await self.listImageVersions(request: request, options: .init())
  }

  public func listImageVersions(
    request: ListImageVersionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudOrchestrationAirflowServiceV1.ListImageVersionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listImageVersionsByItems(
    request: ListImageVersionsRequest
  ) -> some AsyncSequence<ImageVersion, Swift.Error> & Sendable {
    self.listImageVersionsByItems(request: request, options: .init())
  }

  /// List ImageVersions for provided location.
  ///
  /// @Snippet(path: "ImageVersions_ListImageVersions")
  public func listImageVersionsByItems(
    request: ListImageVersionsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<ImageVersion, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudOrchestrationAirflowServiceV1.ListImageVersionsResponse in
      var request = request
      request.pageToken = token
      return try await self.listImageVersions(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listImageVersionsByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<ImageVersion, Swift.Error> & Sendable {
    let request = ListImageVersionsRequest().with {
      $0.parent = parent
    }
    return self.listImageVersionsByItems(request: request)
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ImageVersions_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }
}
