// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Configuration for controlling how IPs are allocated in the
/// GKE cluster running the Apache Airflow software.
public struct IPAllocationPolicy: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Whether or not to enable Alias IPs in the GKE cluster.
  /// If `true`, a VPC-native cluster is created.
  ///
  /// This field is only supported for Cloud Composer environments in versions
  /// composer-1.*.*-airflow-*.*.*. Environments in newer versions always use
  /// VPC-native GKE clusters.
  public var useIpAliases: Swift.Bool = Swift.Bool()

  /// Configuration of allocating IP addresses for pods in the GKE cluster.
  public var clusterIpAllocation: ClusterIpAllocationOneOf? = nil

  /// Configuration of allocating IP addresses for services in the GKE cluster.
  public var servicesIpAllocation: ServicesIpAllocationOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `IPAllocationPolicy`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = IPAllocationPolicy().with { $0.useIpAliases = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let useIpAliases = CodingKeys(stringValue: "useIpAliases")
    static let clusterSecondaryRangeName = CodingKeys(stringValue: "clusterSecondaryRangeName")
    static let clusterIpv4CidrBlock = CodingKeys(stringValue: "clusterIpv4CidrBlock")
    static let servicesSecondaryRangeName = CodingKeys(stringValue: "servicesSecondaryRangeName")
    static let servicesIpv4CidrBlock = CodingKeys(stringValue: "servicesIpv4CidrBlock")

    static let _knownKeys: Set<Swift.String> = [
      "useIpAliases",
      "clusterSecondaryRangeName",
      "clusterIpv4CidrBlock",
      "servicesSecondaryRangeName",
      "servicesIpv4CidrBlock",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .useIpAliases) {
      self.useIpAliases = value
    }

    var clusterIpAllocation: ClusterIpAllocationOneOf? = nil
    let clusterIpAllocationCheckAndSet = {
      if clusterIpAllocation != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'clusterIpAllocation'"))
      }
      clusterIpAllocation = $0
    }
    if let clusterSecondaryRangeName = try container.decodeIfPresent(
      Swift.String.self, forKey: .clusterSecondaryRangeName)
    {
      try clusterIpAllocationCheckAndSet(.clusterSecondaryRangeName(clusterSecondaryRangeName))
    }
    if let clusterIpv4CidrBlock = try container.decodeIfPresent(
      Swift.String.self, forKey: .clusterIpv4CidrBlock)
    {
      try clusterIpAllocationCheckAndSet(.clusterIpv4CidrBlock(clusterIpv4CidrBlock))
    }
    self.clusterIpAllocation = clusterIpAllocation

    var servicesIpAllocation: ServicesIpAllocationOneOf? = nil
    let servicesIpAllocationCheckAndSet = {
      if servicesIpAllocation != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'servicesIpAllocation'"))
      }
      servicesIpAllocation = $0
    }
    if let servicesSecondaryRangeName = try container.decodeIfPresent(
      Swift.String.self, forKey: .servicesSecondaryRangeName)
    {
      try servicesIpAllocationCheckAndSet(.servicesSecondaryRangeName(servicesSecondaryRangeName))
    }
    if let servicesIpv4CidrBlock = try container.decodeIfPresent(
      Swift.String.self, forKey: .servicesIpv4CidrBlock)
    {
      try servicesIpAllocationCheckAndSet(.servicesIpv4CidrBlock(servicesIpv4CidrBlock))
    }
    self.servicesIpAllocation = servicesIpAllocation
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.useIpAliases, forKey: .useIpAliases)

    if let choice = self.clusterIpAllocation {
      switch choice {
      case .clusterSecondaryRangeName(let value):
        try container.encode(value, forKey: .clusterSecondaryRangeName)
      case .clusterIpv4CidrBlock(let value):
        try container.encode(value, forKey: .clusterIpv4CidrBlock)
      }
    }

    if let choice = self.servicesIpAllocation {
      switch choice {
      case .servicesSecondaryRangeName(let value):
        try container.encode(value, forKey: .servicesSecondaryRangeName)
      case .servicesIpv4CidrBlock(let value):
        try container.encode(value, forKey: .servicesIpv4CidrBlock)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Configuration of allocating IP addresses for pods in the GKE cluster.
  public enum ClusterIpAllocationOneOf: Codable, Equatable, Sendable {
    /// Optional. The name of the GKE cluster's secondary range used to allocate
    /// IP addresses to pods.
    ///
    /// For Cloud Composer environments in versions composer-1.*.*-airflow-*.*.*,
    /// this field is applicable only when `use_ip_aliases` is true.
    case clusterSecondaryRangeName(Swift.String)
    /// Optional. The IP address range used to allocate IP addresses to pods in
    /// the GKE cluster.
    ///
    /// For Cloud Composer environments in versions composer-1.*.*-airflow-*.*.*,
    /// this field is applicable only when `use_ip_aliases` is true.
    ///
    /// Set to blank to have GKE choose a range with the default size.
    ///
    /// Set to /netmask (e.g. `/14`) to have GKE choose a range with a specific
    /// netmask.
    ///
    /// Set to a
    /// [CIDR](https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing)
    /// notation (e.g. `10.96.0.0/14`) from the RFC-1918 private networks (e.g.
    /// `10.0.0.0/8`, `172.16.0.0/12`, `192.168.0.0/16`) to pick a specific range
    /// to use.
    case clusterIpv4CidrBlock(Swift.String)
  }

  /// Configuration of allocating IP addresses for services in the GKE cluster.
  public enum ServicesIpAllocationOneOf: Codable, Equatable, Sendable {
    /// Optional. The name of the services' secondary range used to allocate
    /// IP addresses to the GKE cluster.
    ///
    /// For Cloud Composer environments in versions composer-1.*.*-airflow-*.*.*,
    /// this field is applicable only when `use_ip_aliases` is true.
    case servicesSecondaryRangeName(Swift.String)
    /// Optional. The IP address range of the services IP addresses in this
    /// GKE cluster.
    ///
    /// For Cloud Composer environments in versions composer-1.*.*-airflow-*.*.*,
    /// this field is applicable only when `use_ip_aliases` is true.
    ///
    /// Set to blank to have GKE choose a range with the default size.
    ///
    /// Set to /netmask (e.g. `/14`) to have GKE choose a range with a specific
    /// netmask.
    ///
    /// Set to a
    /// [CIDR](https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing)
    /// notation (e.g. `10.96.0.0/14`) from the RFC-1918 private networks (e.g.
    /// `10.0.0.0/8`, `172.16.0.0/12`, `192.168.0.0/16`) to pick a specific range
    /// to use.
    case servicesIpv4CidrBlock(Swift.String)
  }

  /// The type URL for `IPAllocationPolicy`: `"type.googleapis.com/google.cloud.orchestration.airflow.service.v1.IPAllocationPolicy"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.IPAllocationPolicy"
  }

  /// Initialize an instance of `IPAllocationPolicy` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.orchestration.airflow.service.v1.IPAllocationPolicy"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `IPAllocationPolicy` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
