// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleGax
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Response to ListWorkloadsRequest.
public struct ListWorkloadsResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The list of environment workloads.
  public var workloads: [ListWorkloadsResponse.ComposerWorkload] = []

  /// The page token used to query for the next page if one exists.
  public var nextPageToken: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ListWorkloadsResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListWorkloadsResponse().with { $0.workloads = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let workloads = CodingKeys(stringValue: "workloads")
    static let nextPageToken = CodingKeys(stringValue: "nextPageToken")

    static let _knownKeys: Set<Swift.String> = [
      "workloads",
      "nextPageToken",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [ListWorkloadsResponse.ComposerWorkload].self, forKey: .workloads)
    {
      self.workloads = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nextPageToken) {
      self.nextPageToken = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.workloads, forKey: .workloads)
    try container.encode(self.nextPageToken, forKey: .nextPageToken)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Information about a single workload.
  public struct ComposerWorkload: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Name of a workload.
    public var name: Swift.String = Swift.String()

    /// Type of a workload.
    public var type: ListWorkloadsResponse.ComposerWorkloadType =
      ListWorkloadsResponse.ComposerWorkloadType()

    /// Output only. Status of a workload.
    public var status: ListWorkloadsResponse.ComposerWorkloadStatus? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ComposerWorkload`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ComposerWorkload().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let name = CodingKeys(stringValue: "name")
      static let type = CodingKeys(stringValue: "type")
      static let status = CodingKeys(stringValue: "status")

      static let _knownKeys: Set<Swift.String> = [
        "name",
        "type",
        "status",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
        self.name = value
      }
      if let value = try container.decodeIfPresent(
        ListWorkloadsResponse.ComposerWorkloadType.self, forKey: .type)
      {
        self.type = value
      }
      self.status = try container.decodeIfPresent(
        ListWorkloadsResponse.ComposerWorkloadStatus.self, forKey: .status)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.name, forKey: .name)
      try container.encode(self.type, forKey: .type)
      try container.encodeIfPresent(self.status, forKey: .status)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type URL for `ComposerWorkload`: `"type.googleapis.com/google.cloud.orchestration.airflow.service.v1.ListWorkloadsResponse.ComposerWorkload"`.
    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.ListWorkloadsResponse.ComposerWorkload"
    }

    /// Initialize an instance of `ComposerWorkload` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.orchestration.airflow.service.v1.ListWorkloadsResponse.ComposerWorkload"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `ComposerWorkload` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Workload status.
  public struct ComposerWorkloadStatus: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. Workload state.
    public var state: ListWorkloadsResponse.ComposerWorkloadState =
      ListWorkloadsResponse.ComposerWorkloadState()

    /// Output only. Text to provide more descriptive status.
    public var statusMessage: Swift.String = Swift.String()

    /// Output only. Detailed message of the status.
    public var detailedStatusMessage: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ComposerWorkloadStatus`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ComposerWorkloadStatus().with { $0.state = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let state = CodingKeys(stringValue: "state")
      static let statusMessage = CodingKeys(stringValue: "statusMessage")
      static let detailedStatusMessage = CodingKeys(stringValue: "detailedStatusMessage")

      static let _knownKeys: Set<Swift.String> = [
        "state",
        "statusMessage",
        "detailedStatusMessage",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        ListWorkloadsResponse.ComposerWorkloadState.self, forKey: .state)
      {
        self.state = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .statusMessage) {
        self.statusMessage = value
      }
      if let value = try container.decodeIfPresent(
        Swift.String.self, forKey: .detailedStatusMessage)
      {
        self.detailedStatusMessage = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.state, forKey: .state)
      try container.encode(self.statusMessage, forKey: .statusMessage)
      try container.encode(self.detailedStatusMessage, forKey: .detailedStatusMessage)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type URL for `ComposerWorkloadStatus`: `"type.googleapis.com/google.cloud.orchestration.airflow.service.v1.ListWorkloadsResponse.ComposerWorkloadStatus"`.
    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.ListWorkloadsResponse.ComposerWorkloadStatus"
    }

    /// Initialize an instance of `ComposerWorkloadStatus` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.orchestration.airflow.service.v1.ListWorkloadsResponse.ComposerWorkloadStatus"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `ComposerWorkloadStatus` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Supported workload types.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum ComposerWorkloadType: Codable, Equatable, Hashable, Sendable {
    /// Not able to determine the type of the workload.
    case unspecified
    /// Celery worker.
    case celeryWorker
    /// Kubernetes worker.
    case kubernetesWorker
    /// Workload created by Kubernetes Pod Operator.
    case kubernetesOperatorPod
    /// Airflow scheduler.
    case scheduler
    /// Airflow Dag processor.
    case dagProcessor
    /// Airflow triggerer.
    case triggerer
    /// Airflow web server UI.
    case webServer
    /// Redis.
    case redis
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .celeryWorker: return 1
      case .kubernetesWorker: return 2
      case .kubernetesOperatorPod: return 3
      case .scheduler: return 4
      case .dagProcessor: return 5
      case .triggerer: return 6
      case .webServer: return 7
      case .redis: return 8
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "COMPOSER_WORKLOAD_TYPE_UNSPECIFIED"
      case .celeryWorker: return "CELERY_WORKER"
      case .kubernetesWorker: return "KUBERNETES_WORKER"
      case .kubernetesOperatorPod: return "KUBERNETES_OPERATOR_POD"
      case .scheduler: return "SCHEDULER"
      case .dagProcessor: return "DAG_PROCESSOR"
      case .triggerer: return "TRIGGERER"
      case .webServer: return "WEB_SERVER"
      case .redis: return "REDIS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ComposerWorkloadType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "COMPOSER_WORKLOAD_TYPE_UNSPECIFIED": self = .unspecified
      case "CELERY_WORKER": self = .celeryWorker
      case "KUBERNETES_WORKER": self = .kubernetesWorker
      case "KUBERNETES_OPERATOR_POD": self = .kubernetesOperatorPod
      case "SCHEDULER": self = .scheduler
      case "DAG_PROCESSOR": self = .dagProcessor
      case "TRIGGERER": self = .triggerer
      case "WEB_SERVER": self = .webServer
      case "REDIS": self = .redis
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ComposerWorkloadType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .celeryWorker
      case 2: self = .kubernetesWorker
      case 3: self = .kubernetesOperatorPod
      case 4: self = .scheduler
      case 5: self = .dagProcessor
      case 6: self = .triggerer
      case 7: self = .webServer
      case 8: self = .redis
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("COMPOSER_WORKLOAD_TYPE_UNSPECIFIED")
      case .celeryWorker: return try container.encode("CELERY_WORKER")
      case .kubernetesWorker: return try container.encode("KUBERNETES_WORKER")
      case .kubernetesOperatorPod: return try container.encode("KUBERNETES_OPERATOR_POD")
      case .scheduler: return try container.encode("SCHEDULER")
      case .dagProcessor: return try container.encode("DAG_PROCESSOR")
      case .triggerer: return try container.encode("TRIGGERER")
      case .webServer: return try container.encode("WEB_SERVER")
      case .redis: return try container.encode("REDIS")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Workload states.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum ComposerWorkloadState: Codable, Equatable, Hashable, Sendable {
    /// Not able to determine the status of the workload.
    case unspecified
    /// Workload is in pending state and has not yet started.
    case pending
    /// Workload is running fine.
    case ok
    /// Workload is running but there are some non-critical problems.
    case warning
    /// Workload is not running due to an error.
    case error
    /// Workload has finished execution with success.
    case succeeded
    /// Workload has finished execution with failure.
    case failed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .pending: return 1
      case .ok: return 2
      case .warning: return 3
      case .error: return 4
      case .succeeded: return 5
      case .failed: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "COMPOSER_WORKLOAD_STATE_UNSPECIFIED"
      case .pending: return "PENDING"
      case .ok: return "OK"
      case .warning: return "WARNING"
      case .error: return "ERROR"
      case .succeeded: return "SUCCEEDED"
      case .failed: return "FAILED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ComposerWorkloadState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "COMPOSER_WORKLOAD_STATE_UNSPECIFIED": self = .unspecified
      case "PENDING": self = .pending
      case "OK": self = .ok
      case "WARNING": self = .warning
      case "ERROR": self = .error
      case "SUCCEEDED": self = .succeeded
      case "FAILED": self = .failed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ComposerWorkloadState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .pending
      case 2: self = .ok
      case 3: self = .warning
      case 4: self = .error
      case 5: self = .succeeded
      case 6: self = .failed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("COMPOSER_WORKLOAD_STATE_UNSPECIFIED")
      case .pending: return try container.encode("PENDING")
      case .ok: return try container.encode("OK")
      case .warning: return try container.encode("WARNING")
      case .error: return try container.encode("ERROR")
      case .succeeded: return try container.encode("SUCCEEDED")
      case .failed: return try container.encode("FAILED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The type URL for `ListWorkloadsResponse`: `"type.googleapis.com/google.cloud.orchestration.airflow.service.v1.ListWorkloadsResponse"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.ListWorkloadsResponse"
  }

  /// Initialize an instance of `ListWorkloadsResponse` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.orchestration.airflow.service.v1.ListWorkloadsResponse"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `ListWorkloadsResponse` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}

@_spi(GoogleCloudInternal)
extension ListWorkloadsResponse: GoogleGax._PaginatedResponse {
  public func _getPaginatedItems() -> [ListWorkloadsResponse.ComposerWorkload] {
    return self.workloads
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
