// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request to load a snapshot into a Cloud Composer environment.
public struct LoadSnapshotRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The resource name of the target environment in the form:
  /// "projects/{projectId}/locations/{locationId}/environments/{environmentId}"
  public var environment: Swift.String = Swift.String()

  /// A Cloud Storage path to a snapshot to load, e.g.:
  /// "gs://my-bucket/snapshots/project_location_environment_timestamp".
  public var snapshotPath: Swift.String = Swift.String()

  /// Whether or not to skip installing Pypi packages when loading the
  /// environment's state.
  public var skipPypiPackagesInstallation: Swift.Bool = Swift.Bool()

  /// Whether or not to skip setting environment variables when loading the
  /// environment's state.
  public var skipEnvironmentVariablesSetting: Swift.Bool = Swift.Bool()

  /// Whether or not to skip setting Airflow overrides when loading the
  /// environment's state.
  public var skipAirflowOverridesSetting: Swift.Bool = Swift.Bool()

  /// Whether or not to skip copying Cloud Storage data when loading the
  /// environment's state.
  public var skipGcsDataCopying: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `LoadSnapshotRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LoadSnapshotRequest().with { $0.environment = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let environment = CodingKeys(stringValue: "environment")
    static let snapshotPath = CodingKeys(stringValue: "snapshotPath")
    static let skipPypiPackagesInstallation = CodingKeys(
      stringValue: "skipPypiPackagesInstallation")
    static let skipEnvironmentVariablesSetting = CodingKeys(
      stringValue: "skipEnvironmentVariablesSetting")
    static let skipAirflowOverridesSetting = CodingKeys(stringValue: "skipAirflowOverridesSetting")
    static let skipGcsDataCopying = CodingKeys(stringValue: "skipGcsDataCopying")

    static let _knownKeys: Set<Swift.String> = [
      "environment",
      "snapshotPath",
      "skipPypiPackagesInstallation",
      "skipEnvironmentVariablesSetting",
      "skipAirflowOverridesSetting",
      "skipGcsDataCopying",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .environment) {
      self.environment = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .snapshotPath) {
      self.snapshotPath = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .skipPypiPackagesInstallation)
    {
      self.skipPypiPackagesInstallation = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .skipEnvironmentVariablesSetting)
    {
      self.skipEnvironmentVariablesSetting = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .skipAirflowOverridesSetting)
    {
      self.skipAirflowOverridesSetting = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .skipGcsDataCopying) {
      self.skipGcsDataCopying = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.environment, forKey: .environment)
    try container.encode(self.snapshotPath, forKey: .snapshotPath)
    try container.encode(self.skipPypiPackagesInstallation, forKey: .skipPypiPackagesInstallation)
    try container.encode(
      self.skipEnvironmentVariablesSetting, forKey: .skipEnvironmentVariablesSetting)
    try container.encode(self.skipAirflowOverridesSetting, forKey: .skipAirflowOverridesSetting)
    try container.encode(self.skipGcsDataCopying, forKey: .skipGcsDataCopying)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `LoadSnapshotRequest`: `"type.googleapis.com/google.cloud.orchestration.airflow.service.v1.LoadSnapshotRequest"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.LoadSnapshotRequest"
  }

  /// Initialize an instance of `LoadSnapshotRequest` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.orchestration.airflow.service.v1.LoadSnapshotRequest"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `LoadSnapshotRequest` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
