// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Response to PollAirflowCommandRequest.
public struct PollAirflowCommandResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output from the command execution. It may not contain the full output
  /// and the caller may need to poll for more lines.
  public var output: [PollAirflowCommandResponse.Line] = []

  /// Whether the command execution has finished and there is no more output.
  public var outputEnd: Swift.Bool = Swift.Bool()

  /// The result exit status of the command.
  public var exitInfo: PollAirflowCommandResponse.ExitInfo? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `PollAirflowCommandResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PollAirflowCommandResponse().with { $0.output = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let output = CodingKeys(stringValue: "output")
    static let outputEnd = CodingKeys(stringValue: "outputEnd")
    static let exitInfo = CodingKeys(stringValue: "exitInfo")

    static let _knownKeys: Set<Swift.String> = [
      "output",
      "outputEnd",
      "exitInfo",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [PollAirflowCommandResponse.Line].self, forKey: .output)
    {
      self.output = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .outputEnd) {
      self.outputEnd = value
    }
    self.exitInfo = try container.decodeIfPresent(
      PollAirflowCommandResponse.ExitInfo.self, forKey: .exitInfo)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.output, forKey: .output)
    try container.encode(self.outputEnd, forKey: .outputEnd)
    try container.encodeIfPresent(self.exitInfo, forKey: .exitInfo)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Contains information about a single line from logs.
  public struct Line: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Number of the line.
    public var lineNumber: Swift.Int32 = Swift.Int32()

    /// Text content of the log line.
    public var content: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Line`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Line().with { $0.lineNumber = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let lineNumber = CodingKeys(stringValue: "lineNumber")
      static let content = CodingKeys(stringValue: "content")

      static let _knownKeys: Set<Swift.String> = [
        "lineNumber",
        "content",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .lineNumber) {
        self.lineNumber = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .content) {
        self.content = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.lineNumber, forKey: .lineNumber)
      try container.encode(self.content, forKey: .content)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.PollAirflowCommandResponse.Line"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Information about how a command ended.
  public struct ExitInfo: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The exit code from the command execution.
    public var exitCode: Swift.Int32 = Swift.Int32()

    /// Error message. Empty if there was no error.
    public var error: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ExitInfo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ExitInfo().with { $0.exitCode = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let exitCode = CodingKeys(stringValue: "exitCode")
      static let error = CodingKeys(stringValue: "error")

      static let _knownKeys: Set<Swift.String> = [
        "exitCode",
        "error",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .exitCode) {
        self.exitCode = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .error) {
        self.error = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.exitCode, forKey: .exitCode)
      try container.encode(self.error, forKey: .error)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.PollAirflowCommandResponse.ExitInfo"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.PollAirflowCommandResponse"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
