// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The configuration information for configuring a Private IP Cloud Composer
/// environment.
public struct PrivateEnvironmentConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. If `true`, a Private IP Cloud Composer environment is created.
  /// If this field is set to true, `IPAllocationPolicy.use_ip_aliases` must be
  /// set to true for Cloud Composer environments in versions
  /// composer-1.*.*-airflow-*.*.*.
  public var enablePrivateEnvironment: Swift.Bool = Swift.Bool()

  /// Optional. If `true`, builds performed during operations that install Python
  /// packages have only private connectivity to Google services (including
  /// Artifact Registry) and VPC network (if either `NodeConfig.network` and
  /// `NodeConfig.subnetwork` fields or `NodeConfig.composer_network_attachment`
  /// field are specified). If `false`, the builds also have access to the
  /// internet.
  ///
  /// This field is supported for Cloud Composer environments in versions
  /// composer-3-airflow-*.*.*-build.* and newer.
  public var enablePrivateBuildsOnly: Swift.Bool = Swift.Bool()

  /// Optional. Configuration for the private GKE cluster for a Private IP
  /// Cloud Composer environment.
  public var privateClusterConfig: PrivateClusterConfig? = nil

  /// Optional. The CIDR block from which IP range for web server will be
  /// reserved. Needs to be disjoint from
  /// `private_cluster_config.master_ipv4_cidr_block` and
  /// `cloud_sql_ipv4_cidr_block`.
  ///
  /// This field is supported for Cloud Composer environments in versions
  /// composer-1.*.*-airflow-*.*.*.
  public var webServerIpv4CidrBlock: Swift.String = Swift.String()

  /// Optional. The CIDR block from which IP range in tenant project will be
  /// reserved for Cloud SQL. Needs to be disjoint from
  /// `web_server_ipv4_cidr_block`.
  public var cloudSqlIpv4CidrBlock: Swift.String = Swift.String()

  /// Output only. The IP range reserved for the tenant project's App Engine VMs.
  ///
  /// This field is supported for Cloud Composer environments in versions
  /// composer-1.*.*-airflow-*.*.*.
  public var webServerIpv4ReservedRange: Swift.String = Swift.String()

  /// Optional. The CIDR block from which IP range for Cloud Composer Network in
  /// tenant project will be reserved. Needs to be disjoint from
  /// private_cluster_config.master_ipv4_cidr_block and
  /// cloud_sql_ipv4_cidr_block.
  ///
  /// This field is supported for Cloud Composer environments in versions
  /// composer-2.*.*-airflow-*.*.* and newer.
  public var cloudComposerNetworkIpv4CidrBlock: Swift.String = Swift.String()

  /// Output only. The IP range reserved for the tenant project's Cloud Composer
  /// network.
  ///
  /// This field is supported for Cloud Composer environments in versions
  /// composer-2.*.*-airflow-*.*.* and newer.
  public var cloudComposerNetworkIpv4ReservedRange: Swift.String = Swift.String()

  /// Optional. When enabled, IPs from public (non-RFC1918) ranges can be used
  /// for `IPAllocationPolicy.cluster_ipv4_cidr_block` and
  /// `IPAllocationPolicy.service_ipv4_cidr_block`.
  public var enablePrivatelyUsedPublicIps: Swift.Bool = Swift.Bool()

  /// Optional. When specified, the environment will use Private Service Connect
  /// instead of VPC peerings to connect to Cloud SQL in the Tenant Project,
  /// and the PSC endpoint in the Customer Project will use an IP address from
  /// this subnetwork.
  public var cloudComposerConnectionSubnetwork: Swift.String = Swift.String()

  /// Optional. Configuration for the network connections configuration in the
  /// environment.
  public var networkingConfig: NetworkingConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `PrivateEnvironmentConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PrivateEnvironmentConfig().with { $0.enablePrivateEnvironment = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let enablePrivateEnvironment = CodingKeys(stringValue: "enablePrivateEnvironment")
    static let enablePrivateBuildsOnly = CodingKeys(stringValue: "enablePrivateBuildsOnly")
    static let privateClusterConfig = CodingKeys(stringValue: "privateClusterConfig")
    static let webServerIpv4CidrBlock = CodingKeys(stringValue: "webServerIpv4CidrBlock")
    static let cloudSqlIpv4CidrBlock = CodingKeys(stringValue: "cloudSqlIpv4CidrBlock")
    static let webServerIpv4ReservedRange = CodingKeys(stringValue: "webServerIpv4ReservedRange")
    static let cloudComposerNetworkIpv4CidrBlock = CodingKeys(
      stringValue: "cloudComposerNetworkIpv4CidrBlock")
    static let cloudComposerNetworkIpv4ReservedRange = CodingKeys(
      stringValue: "cloudComposerNetworkIpv4ReservedRange")
    static let enablePrivatelyUsedPublicIps = CodingKeys(
      stringValue: "enablePrivatelyUsedPublicIps")
    static let cloudComposerConnectionSubnetwork = CodingKeys(
      stringValue: "cloudComposerConnectionSubnetwork")
    static let networkingConfig = CodingKeys(stringValue: "networkingConfig")

    static let _knownKeys: Set<Swift.String> = [
      "enablePrivateEnvironment",
      "enablePrivateBuildsOnly",
      "privateClusterConfig",
      "webServerIpv4CidrBlock",
      "cloudSqlIpv4CidrBlock",
      "webServerIpv4ReservedRange",
      "cloudComposerNetworkIpv4CidrBlock",
      "cloudComposerNetworkIpv4ReservedRange",
      "enablePrivatelyUsedPublicIps",
      "cloudComposerConnectionSubnetwork",
      "networkingConfig",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enablePrivateEnvironment)
    {
      self.enablePrivateEnvironment = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enablePrivateBuildsOnly)
    {
      self.enablePrivateBuildsOnly = value
    }
    self.privateClusterConfig = try container.decodeIfPresent(
      PrivateClusterConfig.self, forKey: .privateClusterConfig)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .webServerIpv4CidrBlock)
    {
      self.webServerIpv4CidrBlock = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cloudSqlIpv4CidrBlock)
    {
      self.cloudSqlIpv4CidrBlock = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .webServerIpv4ReservedRange)
    {
      self.webServerIpv4ReservedRange = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .cloudComposerNetworkIpv4CidrBlock)
    {
      self.cloudComposerNetworkIpv4CidrBlock = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .cloudComposerNetworkIpv4ReservedRange)
    {
      self.cloudComposerNetworkIpv4ReservedRange = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .enablePrivatelyUsedPublicIps)
    {
      self.enablePrivatelyUsedPublicIps = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .cloudComposerConnectionSubnetwork)
    {
      self.cloudComposerConnectionSubnetwork = value
    }
    self.networkingConfig = try container.decodeIfPresent(
      NetworkingConfig.self, forKey: .networkingConfig)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.enablePrivateEnvironment, forKey: .enablePrivateEnvironment)
    try container.encode(self.enablePrivateBuildsOnly, forKey: .enablePrivateBuildsOnly)
    try container.encodeIfPresent(self.privateClusterConfig, forKey: .privateClusterConfig)
    try container.encode(self.webServerIpv4CidrBlock, forKey: .webServerIpv4CidrBlock)
    try container.encode(self.cloudSqlIpv4CidrBlock, forKey: .cloudSqlIpv4CidrBlock)
    try container.encode(self.webServerIpv4ReservedRange, forKey: .webServerIpv4ReservedRange)
    try container.encode(
      self.cloudComposerNetworkIpv4CidrBlock, forKey: .cloudComposerNetworkIpv4CidrBlock)
    try container.encode(
      self.cloudComposerNetworkIpv4ReservedRange, forKey: .cloudComposerNetworkIpv4ReservedRange)
    try container.encode(self.enablePrivatelyUsedPublicIps, forKey: .enablePrivatelyUsedPublicIps)
    try container.encode(
      self.cloudComposerConnectionSubnetwork, forKey: .cloudComposerConnectionSubnetwork)
    try container.encodeIfPresent(self.networkingConfig, forKey: .networkingConfig)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `PrivateEnvironmentConfig`: `"type.googleapis.com/google.cloud.orchestration.airflow.service.v1.PrivateEnvironmentConfig"`.
  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.PrivateEnvironmentConfig"
  }

  /// Initialize an instance of `PrivateEnvironmentConfig` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.orchestration.airflow.service.v1.PrivateEnvironmentConfig"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `PrivateEnvironmentConfig` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
