// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Configuration options for the private GKE cluster in a Cloud Composer
/// environment.
public struct PrivateClusterConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. If `true`, access to the public endpoint of the GKE cluster is
  /// denied.
  public var enablePrivateEndpoint: Swift.Bool = Swift.Bool()

  /// Optional. The CIDR block from which IPv4 range for GKE master will be
  /// reserved. If left blank, the default value of '172.16.0.0/23' is used.
  public var masterIpv4CidrBlock: Swift.String = Swift.String()

  /// Output only. The IP range in CIDR notation to use for the hosted master
  /// network. This range is used for assigning internal IP addresses to the GKE
  /// cluster master or set of masters and to the internal load balancer virtual
  /// IP. This range must not overlap with any other ranges in use within the
  /// cluster's network.
  public var masterIpv4ReservedRange: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `PrivateClusterConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PrivateClusterConfig().with { $0.enablePrivateEndpoint = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let enablePrivateEndpoint = CodingKeys(stringValue: "enablePrivateEndpoint")
    static let masterIpv4CidrBlock = CodingKeys(stringValue: "masterIpv4CidrBlock")
    static let masterIpv4ReservedRange = CodingKeys(stringValue: "masterIpv4ReservedRange")

    static let _knownKeys: Set<Swift.String> = [
      "enablePrivateEndpoint",
      "masterIpv4CidrBlock",
      "masterIpv4ReservedRange",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enablePrivateEndpoint) {
      self.enablePrivateEndpoint = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .masterIpv4CidrBlock) {
      self.masterIpv4CidrBlock = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .masterIpv4ReservedRange)
    {
      self.masterIpv4ReservedRange = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.enablePrivateEndpoint, forKey: .enablePrivateEndpoint)
    try container.encode(self.masterIpv4CidrBlock, forKey: .masterIpv4CidrBlock)
    try container.encode(self.masterIpv4ReservedRange, forKey: .masterIpv4ReservedRange)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.PrivateClusterConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
