// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The configuration for scheduled snapshot creation mechanism.
public struct ScheduledSnapshotsConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Whether scheduled snapshots creation is enabled.
  public var enabled: Swift.Bool = Swift.Bool()

  /// Optional. The Cloud Storage location for storing automatically created
  /// snapshots.
  public var snapshotLocation: Swift.String = Swift.String()

  /// Optional. The cron expression representing the time when snapshots creation
  /// mechanism runs. This field is subject to additional validation around
  /// frequency of execution.
  public var snapshotCreationSchedule: Swift.String = Swift.String()

  /// Optional. Time zone that sets the context to interpret
  /// snapshot_creation_schedule.
  public var timeZone: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ScheduledSnapshotsConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ScheduledSnapshotsConfig().with { $0.enabled = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let enabled = CodingKeys(stringValue: "enabled")
    static let snapshotLocation = CodingKeys(stringValue: "snapshotLocation")
    static let snapshotCreationSchedule = CodingKeys(stringValue: "snapshotCreationSchedule")
    static let timeZone = CodingKeys(stringValue: "timeZone")

    static let _knownKeys: Set<Swift.String> = [
      "enabled",
      "snapshotLocation",
      "snapshotCreationSchedule",
      "timeZone",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enabled) {
      self.enabled = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .snapshotLocation) {
      self.snapshotLocation = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .snapshotCreationSchedule)
    {
      self.snapshotCreationSchedule = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .timeZone) {
      self.timeZone = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.enabled, forKey: .enabled)
    try container.encode(self.snapshotLocation, forKey: .snapshotLocation)
    try container.encode(self.snapshotCreationSchedule, forKey: .snapshotCreationSchedule)
    try container.encode(self.timeZone, forKey: .timeZone)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `ScheduledSnapshotsConfig`: `"type.googleapis.com/google.cloud.orchestration.airflow.service.v1.ScheduledSnapshotsConfig"`.
  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.ScheduledSnapshotsConfig"
  }

  /// Initialize an instance of `ScheduledSnapshotsConfig` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.orchestration.airflow.service.v1.ScheduledSnapshotsConfig"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `ScheduledSnapshotsConfig` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
