// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Specifies the selection and configuration of software inside the environment.
public struct SoftwareConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. The version of the software running in the environment.
  /// This encapsulates both the version of Cloud Composer functionality and the
  /// version of Apache Airflow. It must match the regular expression
  /// `composer-([0-9]+(\.[0-9]+\.[0-9]+(-preview\.[0-9]+)?)?|latest)-airflow-([0-9]+(\.[0-9]+(\.[0-9]+)?)?)`.
  /// When used as input, the server also checks if the provided version is
  /// supported and denies the request for an unsupported version.
  ///
  /// The Cloud Composer portion of the image version is a full
  /// [semantic version](https://semver.org), or an alias in the form of major
  /// version number or `latest`. When an alias is provided, the server replaces
  /// it with the current Cloud Composer version that satisfies the alias.
  ///
  /// The Apache Airflow portion of the image version is a full semantic version
  /// that points to one of the supported Apache Airflow versions, or an alias in
  /// the form of only major or major.minor versions specified. When an alias is
  /// provided, the server replaces it with the latest Apache Airflow version
  /// that satisfies the alias and is supported in the given Cloud Composer
  /// version.
  ///
  /// In all cases, the resolved image version is stored in the same field.
  ///
  /// See also [version
  /// list](/composer/docs/concepts/versioning/composer-versions) and [versioning
  /// overview](/composer/docs/concepts/versioning/composer-versioning-overview).
  public var imageVersion: Swift.String = Swift.String()

  /// Optional. Apache Airflow configuration properties to override.
  ///
  /// Property keys contain the section and property names, separated by a
  /// hyphen, for example "core-dags_are_paused_at_creation". Section names must
  /// not contain hyphens ("-"), opening square brackets ("["),  or closing
  /// square brackets ("]"). The property name must not be empty and must not
  /// contain an equals sign ("=") or semicolon (";"). Section and property names
  /// must not contain a period ("."). Apache Airflow configuration property
  /// names must be written in
  /// [snake_case](https://en.wikipedia.org/wiki/Snake_case). Property values can
  /// contain any character, and can be written in any lower/upper case format.
  ///
  /// Certain Apache Airflow configuration property values are
  /// [blocked](/composer/docs/concepts/airflow-configurations),
  /// and cannot be overridden.
  public var airflowConfigOverrides: [Swift.String: Swift.String] = [:]

  /// Optional. Custom Python Package Index (PyPI) packages to be installed in
  /// the environment.
  ///
  /// Keys refer to the lowercase package name such as "numpy"
  /// and values are the lowercase extras and version specifier such as
  /// "==1.12.0", "[devel,gcp_api]", or "[devel]>=1.8.2, <1.9.2". To specify a
  /// package without pinning it to a version specifier, use the empty string as
  /// the value.
  public var pypiPackages: [Swift.String: Swift.String] = [:]

  /// Optional. Additional environment variables to provide to the Apache Airflow
  /// scheduler, worker, and webserver processes.
  ///
  /// Environment variable names must match the regular expression
  /// `[a-zA-Z_][a-zA-Z0-9_]*`. They cannot specify Apache Airflow
  /// software configuration overrides (they cannot match the regular expression
  /// `AIRFLOW__[A-Z0-9_]+__[A-Z0-9_]+`), and they cannot match any of the
  /// following reserved names:
  ///
  /// * `AIRFLOW_HOME`
  /// * `C_FORCE_ROOT`
  /// * `CONTAINER_NAME`
  /// * `DAGS_FOLDER`
  /// * `GCP_PROJECT`
  /// * `GCS_BUCKET`
  /// * `GKE_CLUSTER_NAME`
  /// * `SQL_DATABASE`
  /// * `SQL_INSTANCE`
  /// * `SQL_PASSWORD`
  /// * `SQL_PROJECT`
  /// * `SQL_REGION`
  /// * `SQL_USER`
  public var envVariables: [Swift.String: Swift.String] = [:]

  /// Optional. The major version of Python used to run the Apache Airflow
  /// scheduler, worker, and webserver processes.
  ///
  /// Can be set to '2' or '3'. If not specified, the default is '3'. Cannot be
  /// updated.
  ///
  /// This field is only supported for Cloud Composer environments in versions
  /// composer-1.*.*-airflow-*.*.*. Environments in newer versions always use
  /// Python major version 3.
  public var pythonVersion: Swift.String = Swift.String()

  /// Optional. The number of schedulers for Airflow.
  ///
  /// This field is supported for Cloud Composer environments in versions
  /// composer-1.*.*-airflow-2.*.*.
  public var schedulerCount: Swift.Int32 = Swift.Int32()

  /// Optional. The configuration for Cloud Data Lineage integration.
  public var cloudDataLineageIntegration: CloudDataLineageIntegration? = nil

  /// Optional. Whether or not the web server uses custom plugins.
  /// If unspecified, the field defaults to `PLUGINS_ENABLED`.
  ///
  /// This field is supported for Cloud Composer environments in versions
  /// composer-3-airflow-*.*.*-build.* and newer.
  public var webServerPluginsMode: SoftwareConfig.WebServerPluginsMode =
    SoftwareConfig.WebServerPluginsMode()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SoftwareConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SoftwareConfig().with { $0.imageVersion = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let imageVersion = CodingKeys(stringValue: "imageVersion")
    static let airflowConfigOverrides = CodingKeys(stringValue: "airflowConfigOverrides")
    static let pypiPackages = CodingKeys(stringValue: "pypiPackages")
    static let envVariables = CodingKeys(stringValue: "envVariables")
    static let pythonVersion = CodingKeys(stringValue: "pythonVersion")
    static let schedulerCount = CodingKeys(stringValue: "schedulerCount")
    static let cloudDataLineageIntegration = CodingKeys(stringValue: "cloudDataLineageIntegration")
    static let webServerPluginsMode = CodingKeys(stringValue: "webServerPluginsMode")

    static let _knownKeys: Set<Swift.String> = [
      "imageVersion",
      "airflowConfigOverrides",
      "pypiPackages",
      "envVariables",
      "pythonVersion",
      "schedulerCount",
      "cloudDataLineageIntegration",
      "webServerPluginsMode",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .imageVersion) {
      self.imageVersion = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .airflowConfigOverrides)
    {
      self.airflowConfigOverrides = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .pypiPackages)
    {
      self.pypiPackages = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .envVariables)
    {
      self.envVariables = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pythonVersion) {
      self.pythonVersion = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .schedulerCount) {
      self.schedulerCount = value
    }
    self.cloudDataLineageIntegration = try container.decodeIfPresent(
      CloudDataLineageIntegration.self, forKey: .cloudDataLineageIntegration)
    if let value = try container.decodeIfPresent(
      SoftwareConfig.WebServerPluginsMode.self, forKey: .webServerPluginsMode)
    {
      self.webServerPluginsMode = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.imageVersion, forKey: .imageVersion)
    try container.encode(self.airflowConfigOverrides, forKey: .airflowConfigOverrides)
    try container.encode(self.pypiPackages, forKey: .pypiPackages)
    try container.encode(self.envVariables, forKey: .envVariables)
    try container.encode(self.pythonVersion, forKey: .pythonVersion)
    try container.encode(self.schedulerCount, forKey: .schedulerCount)
    try container.encodeIfPresent(
      self.cloudDataLineageIntegration, forKey: .cloudDataLineageIntegration)
    try container.encode(self.webServerPluginsMode, forKey: .webServerPluginsMode)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Web server plugins mode of the Cloud Composer environment.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum WebServerPluginsMode: Codable, Equatable, Hashable, Sendable {
    /// Default mode.
    case unspecified
    /// Web server plugins are not supported.
    case pluginsDisabled
    /// Web server plugins are supported.
    case pluginsEnabled
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .pluginsDisabled: return 1
      case .pluginsEnabled: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "WEB_SERVER_PLUGINS_MODE_UNSPECIFIED"
      case .pluginsDisabled: return "PLUGINS_DISABLED"
      case .pluginsEnabled: return "PLUGINS_ENABLED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:WebServerPluginsMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "WEB_SERVER_PLUGINS_MODE_UNSPECIFIED": self = .unspecified
      case "PLUGINS_DISABLED": self = .pluginsDisabled
      case "PLUGINS_ENABLED": self = .pluginsEnabled
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:WebServerPluginsMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .pluginsDisabled
      case 2: self = .pluginsEnabled
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("WEB_SERVER_PLUGINS_MODE_UNSPECIFIED")
      case .pluginsDisabled: return try container.encode("PLUGINS_DISABLED")
      case .pluginsEnabled: return try container.encode("PLUGINS_ENABLED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.SoftwareConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
