// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Stop Airflow Command request.
public struct StopAirflowCommandRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The resource name of the environment in the form:
  /// "projects/{projectId}/locations/{locationId}/environments/{environmentId}".
  public var environment: Swift.String = Swift.String()

  /// The unique ID of the command execution.
  public var executionId: Swift.String = Swift.String()

  /// The name of the pod where the command is executed.
  public var pod: Swift.String = Swift.String()

  /// The namespace of the pod where the command is executed.
  public var podNamespace: Swift.String = Swift.String()

  /// If true, the execution is terminated forcefully (SIGKILL). If false, the
  /// execution is stopped gracefully, giving it time for cleanup.
  public var force: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `StopAirflowCommandRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StopAirflowCommandRequest().with { $0.environment = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let environment = CodingKeys(stringValue: "environment")
    static let executionId = CodingKeys(stringValue: "executionId")
    static let pod = CodingKeys(stringValue: "pod")
    static let podNamespace = CodingKeys(stringValue: "podNamespace")
    static let force = CodingKeys(stringValue: "force")

    static let _knownKeys: Set<Swift.String> = [
      "environment",
      "executionId",
      "pod",
      "podNamespace",
      "force",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .environment) {
      self.environment = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .executionId) {
      self.executionId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pod) {
      self.pod = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .podNamespace) {
      self.podNamespace = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .force) {
      self.force = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.environment, forKey: .environment)
    try container.encode(self.executionId, forKey: .executionId)
    try container.encode(self.pod, forKey: .pod)
    try container.encode(self.podNamespace, forKey: .podNamespace)
    try container.encode(self.force, forKey: .force)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.StopAirflowCommandRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
