// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The Kubernetes workloads configuration for GKE cluster associated with the
/// Cloud Composer environment. Supported for Cloud Composer environments in
/// versions composer-2.*.*-airflow-*.*.* and newer.
public struct WorkloadsConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Resources used by Airflow schedulers.
  public var scheduler: WorkloadsConfig.SchedulerResource? = nil

  /// Optional. Resources used by Airflow web server.
  public var webServer: WorkloadsConfig.WebServerResource? = nil

  /// Optional. Resources used by Airflow workers.
  public var worker: WorkloadsConfig.WorkerResource? = nil

  /// Optional. Resources used by Airflow triggerers.
  public var triggerer: WorkloadsConfig.TriggererResource? = nil

  /// Optional. Resources used by Airflow DAG processors.
  ///
  /// This field is supported for Cloud Composer environments in versions
  /// composer-3-airflow-*.*.*-build.* and newer.
  public var dagProcessor: WorkloadsConfig.DagProcessorResource? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `WorkloadsConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = WorkloadsConfig().with { $0.scheduler = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let scheduler = CodingKeys(stringValue: "scheduler")
    static let webServer = CodingKeys(stringValue: "webServer")
    static let worker = CodingKeys(stringValue: "worker")
    static let triggerer = CodingKeys(stringValue: "triggerer")
    static let dagProcessor = CodingKeys(stringValue: "dagProcessor")

    static let _knownKeys: Set<Swift.String> = [
      "scheduler",
      "webServer",
      "worker",
      "triggerer",
      "dagProcessor",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.scheduler = try container.decodeIfPresent(
      WorkloadsConfig.SchedulerResource.self, forKey: .scheduler)
    self.webServer = try container.decodeIfPresent(
      WorkloadsConfig.WebServerResource.self, forKey: .webServer)
    self.worker = try container.decodeIfPresent(
      WorkloadsConfig.WorkerResource.self, forKey: .worker)
    self.triggerer = try container.decodeIfPresent(
      WorkloadsConfig.TriggererResource.self, forKey: .triggerer)
    self.dagProcessor = try container.decodeIfPresent(
      WorkloadsConfig.DagProcessorResource.self, forKey: .dagProcessor)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.scheduler, forKey: .scheduler)
    try container.encodeIfPresent(self.webServer, forKey: .webServer)
    try container.encodeIfPresent(self.worker, forKey: .worker)
    try container.encodeIfPresent(self.triggerer, forKey: .triggerer)
    try container.encodeIfPresent(self.dagProcessor, forKey: .dagProcessor)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Configuration for resources used by Airflow schedulers.
  public struct SchedulerResource: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. CPU request and limit for a single Airflow scheduler replica.
    public var cpu: Swift.Float = Swift.Float()

    /// Optional. Memory (GB) request and limit for a single Airflow scheduler
    /// replica.
    public var memoryGb: Swift.Float = Swift.Float()

    /// Optional. Storage (GB) request and limit for a single Airflow scheduler
    /// replica.
    public var storageGb: Swift.Float = Swift.Float()

    /// Optional. The number of schedulers.
    public var count: Swift.Int32 = Swift.Int32()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SchedulerResource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SchedulerResource().with { $0.cpu = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let cpu = CodingKeys(stringValue: "cpu")
      static let memoryGb = CodingKeys(stringValue: "memoryGb")
      static let storageGb = CodingKeys(stringValue: "storageGb")
      static let count = CodingKeys(stringValue: "count")

      static let _knownKeys: Set<Swift.String> = [
        "cpu",
        "memoryGb",
        "storageGb",
        "count",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .cpu) {
        self.cpu = value
      }
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .memoryGb) {
        self.memoryGb = value
      }
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .storageGb) {
        self.storageGb = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .count) {
        self.count = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.cpu, forKey: .cpu)
      try container.encode(self.memoryGb, forKey: .memoryGb)
      try container.encode(self.storageGb, forKey: .storageGb)
      try container.encode(self.count, forKey: .count)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.WorkloadsConfig.SchedulerResource"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration for resources used by Airflow web server.
  public struct WebServerResource: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. CPU request and limit for Airflow web server.
    public var cpu: Swift.Float = Swift.Float()

    /// Optional. Memory (GB) request and limit for Airflow web server.
    public var memoryGb: Swift.Float = Swift.Float()

    /// Optional. Storage (GB) request and limit for Airflow web server.
    public var storageGb: Swift.Float = Swift.Float()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `WebServerResource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = WebServerResource().with { $0.cpu = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let cpu = CodingKeys(stringValue: "cpu")
      static let memoryGb = CodingKeys(stringValue: "memoryGb")
      static let storageGb = CodingKeys(stringValue: "storageGb")

      static let _knownKeys: Set<Swift.String> = [
        "cpu",
        "memoryGb",
        "storageGb",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .cpu) {
        self.cpu = value
      }
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .memoryGb) {
        self.memoryGb = value
      }
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .storageGb) {
        self.storageGb = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.cpu, forKey: .cpu)
      try container.encode(self.memoryGb, forKey: .memoryGb)
      try container.encode(self.storageGb, forKey: .storageGb)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.WorkloadsConfig.WebServerResource"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration for resources used by Airflow workers.
  public struct WorkerResource: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. CPU request and limit for a single Airflow worker replica.
    public var cpu: Swift.Float = Swift.Float()

    /// Optional. Memory (GB) request and limit for a single Airflow worker
    /// replica.
    public var memoryGb: Swift.Float = Swift.Float()

    /// Optional. Storage (GB) request and limit for a single Airflow worker
    /// replica.
    public var storageGb: Swift.Float = Swift.Float()

    /// Optional. Minimum number of workers for autoscaling.
    public var minCount: Swift.Int32 = Swift.Int32()

    /// Optional. Maximum number of workers for autoscaling.
    public var maxCount: Swift.Int32 = Swift.Int32()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `WorkerResource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = WorkerResource().with { $0.cpu = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let cpu = CodingKeys(stringValue: "cpu")
      static let memoryGb = CodingKeys(stringValue: "memoryGb")
      static let storageGb = CodingKeys(stringValue: "storageGb")
      static let minCount = CodingKeys(stringValue: "minCount")
      static let maxCount = CodingKeys(stringValue: "maxCount")

      static let _knownKeys: Set<Swift.String> = [
        "cpu",
        "memoryGb",
        "storageGb",
        "minCount",
        "maxCount",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .cpu) {
        self.cpu = value
      }
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .memoryGb) {
        self.memoryGb = value
      }
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .storageGb) {
        self.storageGb = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .minCount) {
        self.minCount = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .maxCount) {
        self.maxCount = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.cpu, forKey: .cpu)
      try container.encode(self.memoryGb, forKey: .memoryGb)
      try container.encode(self.storageGb, forKey: .storageGb)
      try container.encode(self.minCount, forKey: .minCount)
      try container.encode(self.maxCount, forKey: .maxCount)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.WorkloadsConfig.WorkerResource"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration for resources used by Airflow triggerers.
  public struct TriggererResource: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. The number of triggerers.
    public var count: Swift.Int32 = Swift.Int32()

    /// Optional. CPU request and limit for a single Airflow triggerer replica.
    public var cpu: Swift.Float = Swift.Float()

    /// Optional. Memory (GB) request and limit for a single Airflow triggerer
    /// replica.
    public var memoryGb: Swift.Float = Swift.Float()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `TriggererResource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TriggererResource().with { $0.count = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let count = CodingKeys(stringValue: "count")
      static let cpu = CodingKeys(stringValue: "cpu")
      static let memoryGb = CodingKeys(stringValue: "memoryGb")

      static let _knownKeys: Set<Swift.String> = [
        "count",
        "cpu",
        "memoryGb",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .count) {
        self.count = value
      }
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .cpu) {
        self.cpu = value
      }
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .memoryGb) {
        self.memoryGb = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.count, forKey: .count)
      try container.encode(self.cpu, forKey: .cpu)
      try container.encode(self.memoryGb, forKey: .memoryGb)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.WorkloadsConfig.TriggererResource"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration for resources used by Airflow DAG processors.
  ///
  /// This field is supported for Cloud Composer environments in versions
  /// composer-3-airflow-*.*.*-build.* and newer.
  public struct DagProcessorResource: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. CPU request and limit for a single Airflow DAG processor
    /// replica.
    public var cpu: Swift.Float = Swift.Float()

    /// Optional. Memory (GB) request and limit for a single Airflow DAG
    /// processor replica.
    public var memoryGb: Swift.Float = Swift.Float()

    /// Optional. Storage (GB) request and limit for a single Airflow DAG
    /// processor replica.
    public var storageGb: Swift.Float = Swift.Float()

    /// Optional. The number of DAG processors. If not provided or set to 0, a
    /// single DAG processor instance will be created.
    public var count: Swift.Int32 = Swift.Int32()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `DagProcessorResource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DagProcessorResource().with { $0.cpu = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let cpu = CodingKeys(stringValue: "cpu")
      static let memoryGb = CodingKeys(stringValue: "memoryGb")
      static let storageGb = CodingKeys(stringValue: "storageGb")
      static let count = CodingKeys(stringValue: "count")

      static let _knownKeys: Set<Swift.String> = [
        "cpu",
        "memoryGb",
        "storageGb",
        "count",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .cpu) {
        self.cpu = value
      }
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .memoryGb) {
        self.memoryGb = value
      }
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .storageGb) {
        self.storageGb = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .count) {
        self.count = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.cpu, forKey: .cpu)
      try container.encode(self.memoryGb, forKey: .memoryGb)
      try container.encode(self.storageGb, forKey: .storageGb)
      try container.encode(self.count, forKey: .count)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.WorkloadsConfig.DagProcessorResource"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.orchestration.airflow.service.v1.WorkloadsConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
